import developmental_biology_vascular_development_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace developmental_biology_vascular_development_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end developmental_biology_vascular_development_lemma_canonical_lane_mathlib
end HautevilleHouse
